In [2]:
age=int(input("enter number: "))
if(age>18):
  print("mature")
else:
  print("imature")


imature


In [1]:
## high level operations on files and collection of files
import shutil
shutil.copyfile('source.txt','destination.txt')


'destination.txt'

In [2]:
## data serialization
import json
data={'name':'krish','age':21}
json_str=json.dumps(data)
print(json_str)

{"name": "krish", "age": 21}


In [10]:
##csv
import csv

In [12]:
import csv

# Writing to the CSV file
with open('example.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['name', 'age'])  # Fixed method name
    writer.writerow(['ravi', '21'])

# Reading from the CSV file
with open('example.csv', mode='r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)


['name', 'age']
['ravi', '21']


In [14]:
##datetime
##timedelta=difference between date
from datetime import datetime,timedelta
now=datetime.now()
print(now)
yesterday=now-timedelta(days=1)
print(yesterday)

2024-12-15 20:32:23.453677
2024-12-14 20:32:23.453677


In [15]:
## Regular expression
import re

In [16]:
##Read a whole file
with open('example.txt','r') as file:
    content=file.read()
    print(content)
    

hello sir,
work hard,
work hard.


In [18]:
## writing a file(overwriting)
with open('example.txt','w') as file:
    file.write("hello world")
    file.write("my name is ravi kumar")


In [20]:
## writing file (without overriding )
with open('example.txt','a') as file:
    file.write("\n this is appende ")

In [3]:
##Read a text file and count the number of lines,words,and characters
def count_text_file(file_path):
    with open(file_path,'r') as  file:
        lines=file.readlines()
        line_count=len(lines)
        word_count=sum(len(line.split()) for line in lines)
        char_count=sum(len(line) for line in lines)
    return line_count,word_count,char_count
file_path='example.txt'
lines,words,characters=count_text_file(file_path)
print({lines},{words},{characters})
    


{2} {11} {66}


In [ ]:
#move the file cursor to the beginner
file.seek(0)

In [6]:
##create a new directory
import os
new_directory="package"
os.mkdir(new_directory)

In [7]:
os.rmdir("package")


In [8]:
os.listdir('.')

['basicpython.ipynb',
 'destination.txt',
 'example.csv',
 'example.txt',
 'source.txt']

In [9]:
try:
    a=b
except:
    print("the varible is not ")

the varible is not 


In [10]:
import numpy as np

In [11]:
## create array using numpy
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)


[1 2 3 4 5]
(5,)


In [13]:
arr2=np.array([7,2,3,4,5])
arr2.reshape(1,5)

array([[7, 2, 3, 4, 5]])

In [14]:
np.arange(1,10,4)

array([1, 5, 9])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
arr=np.array([4,9,16,25])
print(np.sqrt(arr))

[2. 3. 4. 5.]


In [19]:
data=np.array([2,3,4,5,6])
mean=np.mean(data)
st_de=np.std(data)
print(mean,st_de)

4.0 1.4142135623730951


In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../Krish Sir Code/Data Analysis With Python/data.csv')

In [3]:
df

Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [4]:
df.head()

Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [5]:
##Data Aggregating and Grouping 
grouped_mean=df.groupby(['Product','Region'])['Value'].sum()
print(grouped_mean)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64


In [6]:
grouped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
print(grouped_agg)

             mean     sum  count
Region                          
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17


In [7]:
##merging and joining dataframe
df1=pd.DataFrame({'Key':['A','B','C'],'Value1':[1,2,3]})
df2=pd.DataFrame({'Key':['A','B','D'],'Value2':[4,5,6]})


In [8]:
print(df1)
print(df2)

  Key  Value1
0   A       1
1   B       2
2   C       3
  Key  Value2
0   A       4
1   B       5
2   D       6


In [13]:
pd.merge(df1,df2,on="Key",how="outer")

Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [14]:
pd.merge(df1,df2,on="Key",how="inner")

Key  Value1  Value2
0   A       1       4
1   B       2       5

In [1]:
import pandas as pd


In [2]:
!pip install lxml

   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -------- ------------------------------- 0.8/3.8 MB 3.7 MB/s eta 0:00:01
   ---------- ----------------------------- 1.0/3.8 MB 3.4 MB/s eta 0:00:01
   ------------- -------------------------- 1.3/3.8 MB 2.2 MB/s eta 0:00:02
   ------------------- -------------------- 1.8/3.8 MB 2.1 MB/s eta 0:00:01
   --------------------- ------------------ 2.1/3.8 MB 2.1 MB/s eta 0:00:01
   --------------------------- ------------ 2.6/3.8 MB 2.0 MB/s eta 0:00:01
   ------------------------------ --------- 2.9/3.8 MB 2.1 MB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 2.0 MB/s eta 0:00:00


In [ ]:
url("")